version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb_school_services
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: alexandre
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_school_services
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alexandre.cano@supdevinci-edu.fr
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  local_pgdata:
  pgadmin-data:
  dbdata6: